config/routes.rb
Rails.application.routes.draw do
  resources :facebook_pages
  get 'bulk-page', to: 'facebook_pages#bulk_fb_page'
	# resources :profiles
    # post 'profiles/create'
    # get 'profiles/update'
    put '/profiles/:id' => 'profiles#update', as: :profile
    get '/profiles/:id/edit' =>  'profiles#edit', as: :edit_profile
    put '/profiles/:id/edit' =>  'profiles#edit'  
    patch  '/profiles/:id(.:format)' => 'profiles#update'
	devise_for :users
	devise_scope :user do
		authenticated :user do
		  root to: "pages#dashboard", as: :authenticated_root
		end

		unauthenticated do
		  root 'pages#index', as: :unauthenticated_root
		end
	end


	get '*path' => redirect('/404.html')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/facebook_page.rb
require 'open-uri'
require 'nokogiri'

class FacebookPage < ApplicationRecord
	belongs_to :user

	def fb_page

	end




end

app/controllers/facebook_pages_controller.rb
require 'open-uri'
require 'nokogiri'

class FacebookPagesController < ApplicationController
  before_action :set_facebook_page, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /facebook_pages
  # GET /facebook_pages.json
  def index
    @facebook_pages = FacebookPage.where(user_id: current_user).all
    @fb_email_only = FacebookPage.where.not(page_email: [nil, ""]).where(page_phone: [nil, ""]).where(user_id: current_user)
    @fb_phone_only = FacebookPage.where.not(page_phone: [nil, ""]).where(page_email: [nil, ""]).where(user_id: current_user)
  end

  def bulk_fb_page
    # @page_name = []
    # @url_page = []
    

    max_page_count = params[:max_page_count]

    max_page_count.to_i.times do |i|
      # @page_total = @page_name.size
      category = params[:category_slugs] #'personal-trainer'

      starting_page = params[:starting_page]
      page_num = starting_page.to_i
      
      url = "https://www.facebook.com/pages/category/#{category}/?page=#{i+page_num}"


      page = Nokogiri::HTML(open(url))

      page.xpath('//comment()').each { |comment| comment.replace(comment.text) }

      code = page.serialize

      @html_doc = Nokogiri::HTML(code)



      # html_doc.css("a._6x0d").each do |item|
      #   #url_page << item["href"]

      #   fb_url = item["href"]
      #   @url_page = fb_url+ "#{'about'}"

      #   fb_page = Nokogiri::HTML(open(@url_page))

      #   @page_title = fb_page.at("meta[property='og:title']")['content'] 

      #   # @page_count = @page_title.size

      #   @page_phone = fb_page.css("#content_container ._50f4").text[/([+|\s]\d+\s\d+[-|\s]\d+[-|\s]\d+|\d+\s\d+\s\d+|\(?\d+\)+\s\d+\s\d+|[\d]{2,}\s[\d]{3,4}[\-]\d+|[\d]{2,3}[\-][\d]{3,4}[\-][\d]{3,4})/i]
      #   @page_email = fb_page.css('a[href^="mailto:"]').text.strip

      
        

      # end


    end
       

  end

  # GET /facebook_pages/1
  # GET /facebook_pages/1.json
  def show
  end

  # GET /facebook_pages/new
  def new
    @facebook_page = FacebookPage.new
  end

  # GET /facebook_pages/1/edit
  def edit
  end

  # POST /facebook_pages
  # POST /facebook_pages.json
  def create
    @facebook_page = FacebookPage.new(facebook_page_params)
    @facebook_page.user_id = current_user.id
    respond_to do |format|
      if @facebook_page.save
        format.html { redirect_to @facebook_page, notice: 'Facebook page was successfully created.' }
        format.json { render :show, status: :created, location: @facebook_page }
      else
        format.html { render :new }
        format.json { render json: @facebook_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facebook_pages/1
  # PATCH/PUT /facebook_pages/1.json
  def update
    respond_to do |format|
      if @facebook_page.update(facebook_page_params)
        format.html { redirect_to @facebook_page, notice: 'Facebook page was successfully updated.' }
        format.json { render :show, status: :ok, location: @facebook_page }
      else
        format.html { render :edit }
        format.json { render json: @facebook_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facebook_pages/1
  # DELETE /facebook_pages/1.json
  def destroy
    @facebook_page.destroy
    respond_to do |format|
      format.html { redirect_to facebook_pages_url, notice: 'Facebook page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facebook_page
      @facebook_page = FacebookPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facebook_page_params
      params.require(:facebook_page).permit(:page_name, :username,:page_phone, :page_email, :page_address, :page_about, :page_mission, :page_url, :page_profile_image, :user_id)
    end
end

app/helpers/facebook_pages_helper.rb
module FacebookPagesHelper
end

app/views/facebook_pages/_all_list.html.erb
<div class="table-responsive">
  <table class="table table-striped table-sm" id="dataTable" width="100%" cellspacing="0">
    <thead>
      <tr>
        <th>Page</th>
        <th>Page Phone</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @facebook_pages.each do |facebook_page| %>
      <tr>
        <td>
          <h6><%= link_to facebook_page.page_name, facebook_page.page_url, target: "_blank", class: "text-dark" %></h6>
          
          <small id="link_action" class="animated--fade-in mb-0">
          <%= link_to 'View', facebook_page %>
          <%= link_to 'Edit', edit_facebook_page_path(facebook_page) %>
          <%= link_to 'Delete', facebook_page, method: :delete, data: { confirm: 'Are you sure?' } %>
          </small>
        </td>
        <td><%= facebook_page.page_phone %></td>
        <td><%= facebook_page.page_email %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  
</div>
<script>
$(document).on('turbolinks:load', function() {
  $(document).ready(function() {
      $('#dataTable').DataTable();
    });
});
</script>

app/views/facebook_pages/_form.html.erb
<div class="row">
  <div class="col-md-9 col-lg-8 col-xl-6 offset-lg-1 offset-xl-2">
    <div class="form-group">
      <%= text_field_tag 'fb_url', nil , class: "form-control facebook_url", placeholder: "Enter Facebook Page UserHandle", id: "facebook_username" %>
      <small class="text-secondary">Sample: (RaketHostPH)</small>
    </div>
  </div>
  <div class="col-md-3 col-lg-2 col-xl-2">
    <div id="fbLink"></div>
    <button class="btn btn-warning float-right btn-pill text-white btn-block get_meta" type="button">
    Get FB Data
    <span class="spinner-border spinner-border-sm" id="loading" role="status" aria-hidden="true"></span>
    </button>
  </div>
</div>
<div class="card mb-4">
  <div class="card-header py-3">
    <div class="d-sm-flex justify-content-between align-items-center">
      <h6 class="m-0 font-weight-bold text-primary"><%= yield :title %></h6>
      <%= yield :edit_button %>
    </div>
  </div>
  <div class="card-body">
<%= form_with(model: facebook_page, local: true) do |form| %>
<% if facebook_page.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(facebook_page.errors.count, "error") %> prohibited this facebook_page from being saved:</h2>
  <ul>
    <% facebook_page.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <div class="card">
            <%#= image_tag asset_path("facebook_page_cover.png"), class: "card-img-top", id: "page_facebook_cover_src" %>
            <div class="card-body">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-lg-3">
                    <% if @facebook_page.page_profile_image.present? %>
                      <%= image_tag @facebook_page.page_profile_image, class: "img-thumbnail", id: "page_profile_image_src" %>
                    <% else %>
                      <%= image_tag asset_path("facebook_page_profile.png"), class: "img-thumbnail", id: "page_profile_image_src" %>
                    <% end -%>

                    <div class="form-group mt-3">
                      <%= form.submit class: "btn btn-primary btn-block" %>
                    </div>
                  </div>
                  <div class="col-lg-9 ">
                    <div class="border-bottom">
                      <h5>
                        <% if @facebook_page.page_url.present? %>

                          <%= link_to @facebook_page.page_url, target: "_blank" do %>
                            <span id="page_name_text"><%= @facebook_page.page_name %></span>
                          <% end %>

                        <% else %>
                          <%= link_to "#", id: "page_url_text" do %>
                            <span id="page_name_text">Your Page Name</span>
                          <% end %>
                        <% end %>
                      </h5>
                      <h6 class="small font-italic">
                      <% if @facebook_page.username.present? %>
                        @<span id="username"><%= @facebook_page.username %></span>
                      <% else %>
                        @<span id="username">NoUsername</span>
                      <% end %>
                      </h6>
                    </div>
                    <div class="border-bottom">
                      <p>
                        <span class="font-weight-bold mr-2">Email </span>
                        <% if @facebook_page.page_email.present? %>
                          <span id="page_email_text"><%= @facebook_page.page_email %></span>
                        <% else %>
                          <span id="page_email_text">noemail@yourdomain.com</span>
                        <% end %>
                      </p>
                    </div>
                    <div class="container-fluid border-bottom">
                      <div class="row">
                        <div class="col-lg-6 m-0 p-0">
                          <div class="row">
                            <div class="col-lg-3 m-0 p-0"><span class="font-weight-bold">Phone</span></div>
                            <div class="col-lg-9 m-0 p-0">
                              <ul>
                                <% if @facebook_page.page_phone.present? %>
                                  <li id="page_phone_text"><%= @facebook_page.page_phone %></li>
                                <% else %>
                                  <li id="page_phone_text">number</li>
                                <% end %>

                                
                                
                              </ul>
                            </div>
                          </div>
                        </div>
                        <div class="col-lg-6 m-0 p-0">
                          <div class="row">
                            <div class="col-lg-3 m-0 p-0"><span class="font-weight-bold">Social</span> </div>
                            <div class="col-lg-9 m-0 p-0">
                              <ul>
                                
                                <li>Twitter</li>
                                <li>Instagram</li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="container-fluid border-bottom p-0">
                      <div class="row">
                        <div class="col-lg-3">
                          <span class="font-weight-bold">Address</span>
                        </div>
                        <% if @facebook_page.page_address.present? %>
                          <div class="col-lg-9" id="page_address_text">
                            <%= @facebook_page.page_address %>
                          </div>
                        <% else %>
                          <div class="col-lg-9" id="page_address_text">
                            No Address
                          </div>
                        <% end %>

                      </div>
                    </div>
                    <div class="container-fluid border-bottom p-0">
                      <div class="row">
                        <div class="col-lg-3">
                          <span class="font-weight-bold">About</span>
                        </div>
                        <% if @facebook_page.page_about.present? %>
                        <div class="col-lg-9" id="page_about_text">
                          <%= @facebook_page.page_about %>
                        </div>

                        <% else %>
                          <div class="col-lg-9" id="page_about_text">
                            No About
                          </div>
                        <% end %>

                      </div>
                    </div>
                    <div class="container-fluid border-bottom m-0 p-0">
                      <div class="row">
                        <div class="col-lg-3">
                          <span class="font-weight-bold">Mission</span>
                        </div>
                        <% if @facebook_page.page_mission.present? %>
                          <div class="col-lg-9" id="page_mission_text">
                            <%= @facebook_page.page_mission %>
                          </div>
                        <% else %>
                          <div class="col-lg-9" id="page_mission_text">
                            Mission
                          </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
<div class="field">
  
  <%= form.hidden_field :page_name, id: :page_name %>
</div>
<div class="field">
  
  <%= form.hidden_field :username, id: :page_username  %>
</div>
<div class="field">
  <%= form.hidden_field :page_phone, id: :page_phone  %>
</div>
<div class="field">

  
  
  <%= form.hidden_field :page_email, id: :page_email %>
</div>
<div class="field">
  
  <%= form.hidden_field :page_address, id: :page_address %>
</div>
<div class="field">
  
  <%= form.hidden_field :page_about, id: :page_about %>
</div>
<div class="field">
  
  <%= form.hidden_field :page_mission, id: :page_mission %>
</div>
<div class="field">
  <%= form.hidden_field :page_url, id: :page_url %>
</div>
<div class="field">
  
  <%= form.hidden_field :page_profile_image, id: :page_profile_image %>
</div>

<% end %>
  </div>
</div>


<script type="text/javascript">
  $('#loading').hide();
  $('button').click(function() {
  $.ajax({
    url: 'https://cors-anywhere.herokuapp.com/' + 'https://www.facebook.com/' + $('.facebook_url').val() + '/about',
    type: 'GET',
    crossDomain: true,
    headers: {
      'Access-Control-Allow-Credentials' : true,
      'Access-Control-Allow-Origin':'*',
      'Access-Control-Allow-Methods':'GET',
      'Access-Control-Allow-Headers':'application/html',
    },
    dataType: "html",
    cache: false,
    beforeSend: function(){
      $('#loading').show();
    },
    complete: function(){
      $('#loading').hide();
    },
    }).then(function(data) {
      var html                    = $(data);

      var numberPattern           = /([+|\s]\d+\s\d+[-|\s]\d+[-|\s]\d+|\d+\s\d+\s\d+|\(?\d+\)+\s\d+\s\d+|[\d]{2,}\s[\d]{3,4}[\-]\d+|[\d]{2,3}[\-][\d]{3,4}[\-][\d]{3,4})/g;

      var title                   = $(html).filter('meta[property="og:title"]').attr("content");
      var url                     = $(html).filter('meta[property="og:url"]').attr("content");
      

      // var phone                   = $(html).find('._3n4o ._50f4').text();
      var phone                   = $(html).find('#content_container ._50f4').text();
      

      var business_phone          = phone.match(numberPattern);

      var address                 = $(html).find('._5aj7 ._2iem').text();
      var about                   = $(html).find('._5po3+ ._3-8j ._3-8w').text();
      var mission                 = $(html).find('._3-8j:nth-child(1) ._3-8w').text();
      var facebook_profile        = $(html).find('img').attr('src');
      var facebook_cover          = $(html).find('#PagesCoverElementContainerPagelet img').attr('src');
      var user_name               = $(html).find('._19s_ div a').text();
      var email                   = $(html).find('a[href^="mailto:"]').text();
      // alert(email);
      
      $('#page_name').val(title);
      $('#page_name_text').text(title);

      $('#page_url').val(url);
      $('#page_url_text').attr('href',url);

      $('#page_phone').val(business_phone);
      $('#page_phone_text').text(business_phone);

      $('#page_address').val(address);
      $('#page_address_text').text(address);

      $('#page_about').val(about);
      $('#page_about_text').text(about);

      $('#page_mission').val(mission);
      $('#page_mission_text').text(mission);

      $('#page_profile_image').val(facebook_profile);
      $('#page_profile_image_src').attr('src',facebook_profile);

      $('#page_facebook_cover').val(facebook_cover);
      $('#page_facebook_cover_src').attr('src',facebook_cover);

      $('#page_email').val(email);
      $('#page_email_text').text(email);
    });
  });
</script>

<script type="text/javascript">
$(document).on('turbolinks:load', function() {
  $(".add_fields").click()

  // Facebook Username
  $('#facebook_username').change(function() {
    $('#username').text($(this).val());
    $('#page_username').val($(this).val());
  });
});
</script>

app/views/facebook_pages/_pill_email_only.html.erb
<div class="table-responsive">
  <table class="table table-striped table-sm" id="dataTablepill" width="100%" cellspacing="0">
    <thead>
      <tr>
        <th>Page</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @fb_email_only.each do |facebook_page| %>
      <tr>
        <td>
          <h6><%= link_to facebook_page.page_name, facebook_page.page_url, target: "_blank", class: "text-dark" %></h6>
          <small id="link_action" class="animated--fade-in mb-0">
          <%= link_to 'View', facebook_page %>
          <%= link_to 'Edit', edit_facebook_page_path(facebook_page) %>
          <%= link_to 'Delete', facebook_page, method: :delete, data: { confirm: 'Are you sure?' } %>
          </small>
        </td>
        <td><%= facebook_page.page_email %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
$(document).on('turbolinks:load', function() {
  $(document).ready(function() {
      $('#dataTablepill').DataTable();
    });
});
</script>

app/views/facebook_pages/_pill_phone_only.html.erb
<div class="table-responsive">
  <table class="table table-striped table-sm" id="dataTablepillphone" width="100%" cellspacing="0">
    <thead>
      <tr>
        <th>Page</th>
        <th>Phone</th>
      </tr>
    </thead>
    <tbody>
      <% @fb_phone_only.each do |facebook_page| %>
      <tr>
        <td>
          <h6><%= link_to facebook_page.page_name, facebook_page.page_url, target: "_blank", class: "text-dark" %></h6>
          <small id="link_action" class="animated--fade-in mb-0">
          <%= link_to 'View', facebook_page %>
          <%= link_to 'Edit', edit_facebook_page_path(facebook_page) %>
          <%= link_to 'Delete', facebook_page, method: :delete, data: { confirm: 'Are you sure?' } %>
          </small>
        </td>
        <td><%= facebook_page.page_phone %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
$(document).on('turbolinks:load', function() {
  $(document).ready(function() {
      $('#dataTablepillphone').DataTable();
    });
});
</script>

app/views/facebook_pages/bulk_fb_page.html.erb
<%= render 'layouts/sidebar' %>
<div id="content-wrapper" class="d-flex flex-column">
  <div id="content">
    <%= render 'layouts/topnav' %>
    <div class="container-fluid">
<div class="container-fluid mb-5">

	<%= form_for(bulk_page_path, :method => "get") do %>
	  <div class="form-row">
	    <div class="col-lg-6">
	    	<label for="inputState">Category <i class="fas fa-question-circle mytooltip" data-toggle="tooltip" data-placement="top" title="Enter Category nam only from Facebook Category"></i></label>

	      
	      <%= text_field_tag :category_slugs, "", value: params[:category_slugs], class: "form-control", placeholder: "Facebook Category" %>
	      <small class="text-secondary">Slugs eg:(personal-trainer)</small>
	      
	    </div>
	    <div class="col-lg-2">
	    	<label for="inputState">Starting Page <i class="fas fa-question-circle mytooltip" data-toggle="tooltip" data-placement="top" title="Starting page to save"></i></label>
	      
	      <%= number_field_tag :starting_page, "", value: params[:starting_page], class: "form-control", placeholder: "Starting Page" %>
	    </div>
	    <div class="col-lg-2">
	    	<label for="inputState">Max Page Count <i class="fas fa-question-circle mytooltip" data-toggle="tooltip" data-placement="top" title="Number of pagination"></i></label>
	      <%= number_field_tag :max_page_count, "", value: params[:max_page_count], class: "form-control", placeholder: "Max Page" %>
	    </div>
	    <div class="col-lg-2">
	    	<label for="inputState">&nbsp; </label><br>
	    	<%= submit_tag "Get Page", class: "btn btn-warning" %>
	      
	    </div>
	  </div>
	<% end -%>
</div>
			
		<ol class="list-group mb-3">
	    	<% @html_doc.css("a._6x0d").each do |item| %>
	    		<li class="list-group-item">
	    			
	    			<% fb_page = Nokogiri::HTML(open(item["href"]+ "#{'about'}")) %>

      				<h6 class="font-weight-bold"><%= link_to fb_page.at("meta[property='og:title']")['content'],item["href"]+ "#{'about'}", target: "_blank" %></h6>
      				<p class="mb-0 p-0">Phone: <%= @page_phone = fb_page.css("#content_container ._50f4").text[/([+|\s]\d+\s\d+[-|\s]\d+[-|\s]\d+|\d+\s\d+\s\d+|\(?\d+\)+\s\d+\s\d+|[\d]{2,}\s[\d]{3,4}[\-]\d+|[\d]{2,3}[\-][\d]{3,4}[\-][\d]{3,4})/i] %></p>

     
      				<p>Email: <%= @page_email = fb_page.css('a[href^="mailto:"]').text.strip %></p>
	    		
	    				
	    		</li>
	    	<% end %>
    	</ol>
		
	</div>
  </div>
	<%= render 'layouts/footer' %>
</div>
<script type="text/javascript">
	$('.mytooltip').tooltip()
</script>

app/views/facebook_pages/edit.html.erb
<%= render 'layouts/sidebar' %>
<% content_for :edit_button do %>
<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
	<div class="btn-group mr-2" role="group" aria-label="First group">
		<%= link_to 'View', @facebook_page, class: "btn btn-success btn-sm d-none d-sm-inline-block", role: "button" %>
		
	</div>
	<div class="btn-group mr-2" role="group" aria-label="Second group">
		<%= link_to 'Back', facebook_pages_path, class: "btn btn-primary btn-sm d-none d-sm-inline-block", role: "button" %>
	</div>
</div>
<% end -%>
<div id="content-wrapper" class="d-flex flex-column">
  <div id="content">
    <%= render 'layouts/topnav' %>
    <div class="container-fluid">
		<h1><% content_for :title, "Edit Facebook Page" %></h1>

		<%= render 'form', facebook_page: @facebook_page %>
	</div>
  </div>
  
  <%= render 'layouts/footer' %>
</div>

app/views/facebook_pages/new.html.erb
<%= render 'layouts/sidebar' %>
<div id="content-wrapper" class="d-flex flex-column">
  <div id="content">
    <%= render 'layouts/topnav' %>
    <div class="container-fluid">
		<h1 class="text-dark"><% content_for :title, "Add Facebook Page" %></h1>

		<%= render 'form', facebook_page: @facebook_page %>
	</div>
  </div>
  
  <%= render 'layouts/footer' %>
</div>

app/views/facebook_pages/show.html.erb
<%= render 'layouts/sidebar' %>
<% content_for :edit_button do %>
<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
  <div class="btn-group mr-2" role="group" aria-label="First group">
    <%= link_to 'Edit', edit_facebook_page_path(@facebook_page), class: "btn btn-warning btn-sm d-none d-sm-inline-block", role: "button" %>
    
  </div>
  <div class="btn-group mr-2" role="group" aria-label="Second group">
    <%= link_to 'Back', facebook_pages_path, class: "btn btn-primary btn-sm d-none d-sm-inline-block", role: "button" %>
  </div>
</div>
<% end -%>

<div id="content-wrapper" class="d-flex flex-column">
  <div id="content">
    <%= render 'layouts/topnav' %>

<div class="container-fluid">
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <div class="card">
            <%#= image_tag asset_path("facebook_page_cover.png"), class: "card-img-top", id: "page_facebook_cover_src" %>
            <div class="card-header py-3">
              <div class="d-sm-flex justify-content-between align-items-center">
                <h6 class="m-0 font-weight-bold text-primary"></h6>
                <%= yield :edit_button %>
              </div>
            </div>
            <div class="card-body">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-lg-3">
                    <% if @facebook_page.page_profile_image.present? %>
                      <%= image_tag @facebook_page.page_profile_image, class: "img-thumbnail", id: "page_profile_image_src" %>
                    <% else %>
                      <%= image_tag asset_path("facebook_page_profile.png"), class: "img-thumbnail", id: "page_profile_image_src" %>
                    <% end -%>

                    
                  </div>
                  <div class="col-lg-9 ">
                    <div class="border-bottom">
                      <h5>
                        <% if @facebook_page.page_url.present? %>

                        <%= link_to @facebook_page.page_url, target: "_blank" do %>
                          <span id="page_name_text"><%= @facebook_page.page_name %></span>
                        <% end %>

                        <% else %>
                        <%= link_to "#" do %>
                          <span id="page_name_text">Your Page Name</span>
                        <% end %>
                        <% end -%>
                      </h5>
                      <h6 class="small font-italic">
                      <% if @facebook_page.username.present? %>
                        @<span id="username"><%= @facebook_page.username %></span>
                      <% else %>
                        @<span id="username">NoUsername</span>
                      <% end %>
                      </h6>
                    </div>
                    <div class="border-bottom">
                      <p>
                        <span class="font-weight-bold mr-2">Email </span>
                        <% if @facebook_page.page_email.present? %>
                          <span id="page_email_text"><%= @facebook_page.page_email %></span>
                        <% else %>
                          <span id="page_email_text">noemail@yourdomain.com</span>
                        <% end %>
                      </p>
                    </div>
                    <div class="container-fluid border-bottom">
                      <div class="row">
                        <div class="col-lg-6 m-0 p-0">
                          <div class="row">
                            <div class="col-lg-3 m-0 p-0"><span class="font-weight-bold">Phone</span></div>
                            <div class="col-lg-9 m-0 p-0">
                              <ul>
                                <% if @facebook_page.page_phone.present? %>
                                  <li><%= @facebook_page.page_phone %></li>
                                <% else %>
                                  <li>number</li>
                                <% end %>

                                
                              </ul>
                            </div>
                          </div>
                        </div>
                        <div class="col-lg-6 m-0 p-0">
                          <div class="row">
                            <div class="col-lg-3 m-0 p-0"><span class="font-weight-bold">Social</span> </div>
                            <div class="col-lg-9 m-0 p-0">
                              <ul>
                                
                                <li>Twitter</li>
                                <li>Instagram</li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="container-fluid border-bottom p-0">
                      <div class="row">
                        <div class="col-lg-3">
                          <span class="font-weight-bold">Address</span>
                        </div>
                        <% if @facebook_page.page_address.present? %>
                          <div class="col-lg-9" id="page_address_text">
                            <%= @facebook_page.page_address %>
                          </div>
                        <% else %>
                          <div class="col-lg-9" id="page_address_text">
                            No Address
                          </div>
                        <% end %>

                      </div>
                    </div>
                    <div class="container-fluid border-bottom p-0">
                      <div class="row">
                        <div class="col-lg-3">
                          <span class="font-weight-bold">About</span>
                        </div>
                        <% if @facebook_page.page_about.present? %>
                        <div class="col-lg-9" id="page_about_text">
                          <%= @facebook_page.page_about %>
                        </div>

                        <% else %>
                          <div class="col-lg-9" id="page_about_text">
                            No About
                          </div>
                        <% end %>

                      </div>
                    </div>
                    <div class="container-fluid border-bottom m-0 p-0">
                      <div class="row">
                        <div class="col-lg-3">
                          <span class="font-weight-bold">Mission</span>
                        </div>
                        <% if @facebook_page.page_mission.present? %>
                          <div class="col-lg-9" id="page_mission_text">
                            <%= @facebook_page.page_mission %>
                          </div>
                        <% else %>
                          <div class="col-lg-9" id="page_mission_text">
                            Mission
                          </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>




  </div>
  
  <%= render 'layouts/footer' %>
</div>