config/routes.rb
Rails.application.routes.draw do
  resources :facebook_pages
  get 'bulk-page', to: 'facebook_pages#bulk_fb_page'
	# resources :profiles
    # post 'profiles/create'
    # get 'profiles/update'
    put '/profiles/:id' => 'profiles#update', as: :profile
    get '/profiles/:id/edit' =>  'profiles#edit', as: :edit_profile
    put '/profiles/:id/edit' =>  'profiles#edit'  
    patch  '/profiles/:id(.:format)' => 'profiles#update'
	devise_for :users
	devise_scope :user do
		authenticated :user do
		  root to: "pages#dashboard", as: :authenticated_root
		end

		unauthenticated do
		  root 'pages#index', as: :unauthenticated_root
		end
	end


	get '*path' => redirect('/404.html')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
  <!-- Footer -->
  <footer class="sticky-footer bg-white">
    <div class="container my-auto">
      <div class="copyright text-center my-auto">
        <span>Copyright © <%= app_name %> <%= year %></span>
      </div>
    </div>
  </footer>
  <!-- End of Footer -->

app/views/layouts/_outer_nav.html.erb
<nav class="navbar navbar-light navbar-expand-md navigation-clean-button py-3 border-bottom">
	<div class="container">
		<h3 class="pt-1">
			<%= link_to unauthenticated_root_path, class: "navbar-brand" do %>
			<%= image_tag asset_path("gleadr-logo.png"), with: "40", height: "40" %>
				<span class="text-danger"><%= app_name %></span>
			<% end %>
		</h3>
		
		<button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
			<span class="sr-only">Toggle navigation</span>
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navcol-1">
			<ul class="nav navbar-nav">
				
				<li class="nav-item">
					<%= link_to "#", class: " nav-link" do %>
					Product
					<% end %>
				</li>
				
				<li class="nav-item">
					<%= link_to "#", class: "nav-link" do %>
					Pricing
					<% end %>
				</li>
				
			</ul>
		</div>

		<div class="collapse navbar-collapse" id="navcol-1">
			<ul class="nav navbar-nav ml-auto">
				<% if user_signed_in? %>
				<li class="nav-item">
					<%= link_to destroy_user_session_path, method: :delete, class: "btn btn-danger nav-link rounded-pill" do %>
					Logout
					<% end %>
				</li>
				<% else %>
				<li class="nav-item">
					<%= link_to "Login", new_user_session_path, class: "btn btn-link text-dark mx-1", role: "button" %>
				</li>
				<li class="nav-item">
					<%= link_to "Sign up", new_user_registration_path, class: "btn btn-danger", role: "button" %>
				</li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <%= link_to authenticated_root_path, class: "sidebar-brand d-flex align-items-center justify-content-center" do %>
      
        <div class="sidebar-brand-icon rotate-n-15">
          
        </div>
        <div class="sidebar-brand-text mx-3"><%= image_tag asset_path("gleadr-logo.png"), with: "40", height: "40" %>
           <%= app_name %></div>
      <% end -%>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
      	<%= link_to authenticated_root_path, class: "nav-link" do %>
      	<i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span>
      	<% end %>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseStore" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fab fa-facebook"></i>

          <span>Facebook</span>
        </a>
        <div id="collapseStore" class="collapse" aria-labelledby="headingStore" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <%= link_to facebook_pages_path, class: "collapse-item" do %>
              All Facebook Page
            <% end %>
            <%= link_to new_facebook_page_path, class: "collapse-item" do %>
              Add New Page
            <% end %>
            <%= link_to bulk_page_path, class: "collapse-item" do %>
              Get Bulk Fb Page
            <% end %>

            
            
          </div>
        </div>
      </li>

      


      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>

app/views/layouts/_topnav.html.erb
  <!-- Topbar -->
  <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
      <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-dark" type="button">
          <i class="fas fa-search fa-sm"></i>
          </button>
        </div>
      </div>
    </form>
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
      <!-- Nav Item - Search Dropdown (Visible Only XS) -->
      <li class="nav-item dropdown no-arrow d-sm-none">
        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-search fa-fw"></i>
        </a>
        <!-- Dropdown - Messages -->
        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
          <form class="form-inline mr-auto w-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow">
        <div class="nav-link ">
        <%= link_to new_facebook_page_path, class: "d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm " do %>
        Add Page
        <% end %>
        </div>
      </li>
      <div class="topbar-divider d-none d-sm-block"></div>
      <!-- Nav Item - User Information -->
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= my_name %></span>

          <% if current_user.profile.avatar.nil? %>
            <%= image_tag asset_path("avatar_2x.png"), class: "img-profile rounded-circle" %>
          <% else %>
            <%= image_tag current_user.profile.avatar_url(:profile_medium).to_s, class: "img-profile rounded-circle" %>
          <% end %>

        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
          <%= link_to edit_profile_path(current_user), class: "dropdown-item" do %>
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            Profile
          <% end %>
          <div class="dropdown-divider"></div>

            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item", "data-toggle": "modal", "data-target": "#logoutModal" do %>
              <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
              Logout
            <% end %>

          
        </div>
      </li>
    </ul>
  </nav>
  <!-- End of Topbar -->
  <!-- Begin Page Content -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="title" content="<%= app_name %> | Get Leads From Any Social Media Sites.">
    <meta name="description" content="<%= app_name %> let you collect phone, emails and websites from any social media sites easily and connect the people that matter for your business.">

    <meta property="og:title" content="<%= app_name %> | Get Leads From Any Social Media Sites.">
    <meta property="og:description" content="<%= app_name %> let you collect phone, emails and websites from any social media sites easily and connect the people that matter for your business.">
    <meta property="og:image" content="<%= default_fb_image %>">
    <meta property="og:url" content="<%= authenticated_root_path %>">

    <meta name="twitter:title" content="<%= app_name %> | Get Leads From Any Social Media Sites.">
    <meta name="twitter:description" content="<%= app_name %> let you collect phone, emails and websites from any social media sites easily and connect the people that matter for your business.">
    <meta name="twitter:image" content=" <%= default_fb_image %>">
    <meta name="twitter:card" content="<%= default_fb_image %>">

    <title><%= app_name %> | Get Leads From Any Social Media Sites.</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Begin Inspectlet Asynchronous Code -->
    <script type="text/javascript">
    (function() {
    window.__insp = window.__insp || [];
    __insp.push(['wid', 1034428822]);
    var ldinsp = function(){
    if(typeof window.__inspld != "undefined") return; window.__inspld = 1; var insp = document.createElement('script'); insp.type = 'text/javascript'; insp.async = true; insp.id = "inspsync"; insp.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://cdn.inspectlet.com/inspectlet.js?wid=1034428822&r=' + Math.floor(new Date().getTime()/3600000); var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(insp, x); };
    setTimeout(ldinsp, 0);
    })();
    </script>
    <!-- End Inspectlet Asynchronous Code -->
  
  </head>
  <body id="page-top" class="<%= yield :page_class %>">
    <div id="wrapper">
        
        <%= yield %>

    </div>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143532643-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-143532643-1');
    </script>


  </body>
</html>